#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require_relative 'astParser.rb'
require_relative 'Lexer.rb'
 

class Parser < Racc::Parser

module_eval(<<'...end Parser.y/module_eval...', 'Parser.y', 221)
    
    def initialize(lexer)
        @lexer = lexer
    end

    def on_error(id, token, stack)
    	@TokenClass = Object::const_get("#{CaracterInesperado}") #Se crea un nueva instacia de error
        error = @TokenClass.new(token.valor, token.linea, token.columna)
      	puts error
      	return
    end
    
    def next_token
        if @lexer.tiene_token then
            token = @lexer.siguiente_token;
            return [token.class, token]
        else
            return nil
        end
    end

    def parse
        do_parse
    end
...end Parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    42,    33,     5,   123,    45,    33,    42,    44,     8,    41,
    45,   124,   134,    44,    42,    41,    43,    25,    45,   133,
    42,    44,    43,    41,    45,   -17,    58,    44,    42,    41,
    43,    59,    45,     3,     4,    44,    43,    41,    63,    26,
    27,    24,    30,    35,    43,    36,    31,    49,    50,    24,
    47,    48,    37,    49,    50,    24,    47,    48,    24,    24,
     8,    49,    50,    24,    47,    48,    57,    49,    50,    24,
    47,    48,    61,    64,    87,    49,    50,    24,    47,    48,
    42,    88,    89,    31,    45,    24,    42,    44,    98,    41,
    45,   116,   119,    44,    42,    41,    43,   120,    45,    33,
    42,    44,    43,    41,    45,   122,   125,    44,    42,    41,
    43,   126,    45,    24,   131,    44,    43,    41,    94,   132,
   135,    91,    92,    93,    43,   139,   140,    49,    50,    24,
    47,    48,   142,    49,    50,    24,    47,    48,   nil,   nil,
   nil,    49,    50,    24,    47,    48,   nil,    49,    50,    24,
    47,    48,   nil,   nil,   nil,    49,    50,    24,    47,    48,
    42,   nil,   nil,   nil,    45,   nil,    42,    44,   nil,    41,
    45,   nil,   nil,    44,    42,    41,    43,   nil,    45,   nil,
    42,    44,    43,    41,    45,   nil,   nil,    44,    42,    41,
    43,   nil,    45,   nil,   nil,    44,    43,    41,    94,   nil,
   nil,    91,    92,    93,    43,   nil,   nil,    49,    50,    24,
    47,    48,   nil,    49,    50,    24,    47,    48,   nil,   nil,
   nil,    49,    50,    24,    47,    48,   nil,    49,    50,    24,
    47,    48,   nil,   nil,   nil,    49,    50,    24,    47,    48,
    42,   nil,   nil,   nil,    45,   nil,    42,    44,   nil,    41,
    45,   nil,   nil,    44,    42,    41,    43,   nil,    45,   nil,
    42,    44,    43,    41,    45,   nil,   nil,    44,    42,    41,
    43,   nil,    45,   nil,   nil,    44,    43,    41,   nil,   nil,
   nil,   nil,   nil,   nil,    43,   nil,   nil,    49,    50,    24,
    47,    48,   nil,    49,    50,    24,    47,    48,   nil,   nil,
   nil,    49,    50,    24,    47,    48,   nil,    49,    50,    24,
    47,    48,   nil,   nil,   nil,    49,    50,    24,    47,    48,
    42,   nil,   nil,   nil,    45,   nil,    42,    44,   nil,    41,
    45,   nil,   nil,    44,    42,    41,    43,   nil,    45,   nil,
    42,    44,    43,    41,    45,   nil,   nil,    44,    42,    41,
    43,   nil,    45,   nil,   nil,    44,    43,    41,   nil,   nil,
   nil,   nil,   nil,   nil,    43,   nil,   nil,    49,    50,    24,
    47,    48,   nil,    49,    50,    24,    47,    48,   nil,   nil,
   nil,    49,    50,    24,    47,    48,   nil,    49,    50,    24,
    47,    48,   nil,   nil,   nil,    49,    50,    24,    47,    48,
    42,   nil,   nil,   nil,    45,   nil,    42,    44,   nil,    41,
    45,   nil,   nil,    44,    42,    41,    43,   nil,    45,   nil,
    42,    44,    43,    41,    45,   nil,   nil,    44,    42,    41,
    43,   nil,    45,   nil,   nil,    44,    43,    41,   nil,   nil,
   nil,   nil,   nil,   nil,    43,   nil,   nil,    49,    50,    24,
    47,    48,   nil,    49,    50,    24,    47,    48,   nil,   nil,
   nil,    49,    50,    24,    47,    48,   nil,    49,    50,    24,
    47,    48,   nil,   nil,   nil,    49,    50,    24,    47,    48,
    42,   nil,   nil,   nil,    45,   nil,    42,    44,   nil,    41,
    45,   nil,   nil,    44,   nil,    41,    43,   nil,   nil,   nil,
   nil,    75,    43,    73,    74,   nil,    66,    67,    68,    69,
    70,   nil,    71,    72,   nil,    76,    77,    78,    79,    80,
    81,   nil,   nil,   nil,   nil,   nil,   nil,    49,    50,    24,
    47,    48,   nil,    49,    50,    24,    47,    48,     3,     4,
    65,   nil,   nil,   nil,   nil,   nil,   nil,    19,   nil,    20,
    21,     3,     4,   nil,    22,    23,   nil,   nil,   nil,   nil,
    19,   nil,    20,    21,    24,   nil,   nil,    22,    23,     3,
     4,   nil,   nil,   nil,   nil,   nil,   nil,    24,    19,   nil,
    20,    21,     3,     4,   nil,    22,    23,   nil,   nil,   nil,
   nil,    19,   nil,    20,    21,    24,   nil,   nil,    22,    23,
     3,     4,   nil,   nil,   nil,   nil,   nil,   nil,    24,    19,
   nil,    20,    21,     3,     4,   nil,    22,    23,   nil,   nil,
   nil,   nil,    19,   nil,    20,    21,    24,   nil,   nil,    22,
    23,     3,     4,   nil,   nil,   nil,   nil,   nil,   nil,    24,
    19,   nil,    20,    21,     3,     4,   nil,    22,    23,   nil,
   nil,   nil,   nil,    19,   nil,    20,    21,    24,   nil,   nil,
    22,    23,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    24 ]

racc_action_check = [
    19,    10,     1,   100,    19,   122,    20,    19,     3,    19,
    20,   100,   130,    20,    23,    20,    19,     5,    23,   130,
    31,    23,    20,    23,    31,   122,    29,    31,    33,    31,
    23,    29,    33,     0,     0,    33,    31,    33,    38,     6,
     7,     8,     9,    12,    33,    17,    10,    19,    19,    19,
    19,    19,    18,    20,    20,    20,    20,    20,    21,    22,
    27,    23,    23,    23,    23,    23,    28,    31,    31,    31,
    31,    31,    32,    39,    51,    33,    33,    33,    33,    33,
    41,    52,    55,    38,    41,    58,    42,    41,    62,    41,
    42,    83,    94,    42,    43,    42,    41,    96,    43,    98,
    44,    43,    42,    43,    44,    99,   117,    44,    45,    44,
    43,   118,    45,   120,   127,    45,    44,    45,    57,   129,
   131,    57,    57,    57,    45,   136,   137,    41,    41,    41,
    41,    41,   141,    42,    42,    42,    42,    42,   nil,   nil,
   nil,    43,    43,    43,    43,    43,   nil,    44,    44,    44,
    44,    44,   nil,   nil,   nil,    45,    45,    45,    45,    45,
    59,   nil,   nil,   nil,    59,   nil,    61,    59,   nil,    59,
    61,   nil,   nil,    61,    63,    61,    59,   nil,    63,   nil,
    65,    63,    61,    63,    65,   nil,   nil,    65,    66,    65,
    63,   nil,    66,   nil,   nil,    66,    65,    66,   135,   nil,
   nil,   135,   135,   135,    66,   nil,   nil,    59,    59,    59,
    59,    59,   nil,    61,    61,    61,    61,    61,   nil,   nil,
   nil,    63,    63,    63,    63,    63,   nil,    65,    65,    65,
    65,    65,   nil,   nil,   nil,    66,    66,    66,    66,    66,
    67,   nil,   nil,   nil,    67,   nil,    68,    67,   nil,    67,
    68,   nil,   nil,    68,    69,    68,    67,   nil,    69,   nil,
    70,    69,    68,    69,    70,   nil,   nil,    70,    71,    70,
    69,   nil,    71,   nil,   nil,    71,    70,    71,   nil,   nil,
   nil,   nil,   nil,   nil,    71,   nil,   nil,    67,    67,    67,
    67,    67,   nil,    68,    68,    68,    68,    68,   nil,   nil,
   nil,    69,    69,    69,    69,    69,   nil,    70,    70,    70,
    70,    70,   nil,   nil,   nil,    71,    71,    71,    71,    71,
    72,   nil,   nil,   nil,    72,   nil,    75,    72,   nil,    72,
    75,   nil,   nil,    75,    76,    75,    72,   nil,    76,   nil,
    77,    76,    75,    76,    77,   nil,   nil,    77,    78,    77,
    76,   nil,    78,   nil,   nil,    78,    77,    78,   nil,   nil,
   nil,   nil,   nil,   nil,    78,   nil,   nil,    72,    72,    72,
    72,    72,   nil,    75,    75,    75,    75,    75,   nil,   nil,
   nil,    76,    76,    76,    76,    76,   nil,    77,    77,    77,
    77,    77,   nil,   nil,   nil,    78,    78,    78,    78,    78,
    79,   nil,   nil,   nil,    79,   nil,    80,    79,   nil,    79,
    80,   nil,   nil,    80,    81,    80,    79,   nil,    81,   nil,
    88,    81,    80,    81,    88,   nil,   nil,    88,   119,    88,
    81,   nil,   119,   nil,   nil,   119,    88,   119,   nil,   nil,
   nil,   nil,   nil,   nil,   119,   nil,   nil,    79,    79,    79,
    79,    79,   nil,    80,    80,    80,    80,    80,   nil,   nil,
   nil,    81,    81,    81,    81,    81,   nil,    88,    88,    88,
    88,    88,   nil,   nil,   nil,   119,   119,   119,   119,   119,
   126,   nil,   nil,   nil,   126,   nil,   134,   126,   nil,   126,
   134,   nil,   nil,   134,   nil,   134,   126,   nil,   nil,   nil,
   nil,    40,   134,    40,    40,   nil,    40,    40,    40,    40,
    40,   nil,    40,    40,   nil,    40,    40,    40,    40,    40,
    40,   nil,   nil,   nil,   nil,   nil,   nil,   126,   126,   126,
   126,   126,   nil,   134,   134,   134,   134,   134,     4,     4,
    40,   nil,   nil,   nil,   nil,   nil,   nil,     4,   nil,     4,
     4,    11,    11,   nil,     4,     4,   nil,   nil,   nil,   nil,
    11,   nil,    11,    11,     4,   nil,   nil,    11,    11,    26,
    26,   nil,   nil,   nil,   nil,   nil,   nil,    11,    26,   nil,
    26,    26,    64,    64,   nil,    26,    26,   nil,   nil,   nil,
   nil,    64,   nil,    64,    64,    26,   nil,   nil,    64,    64,
    87,    87,   nil,   nil,   nil,   nil,   nil,   nil,    64,    87,
   nil,    87,    87,   124,   124,   nil,    87,    87,   nil,   nil,
   nil,   nil,   124,   nil,   124,   124,    87,   nil,   nil,   124,
   124,   133,   133,   nil,   nil,   nil,   nil,   nil,   nil,   124,
   133,   nil,   133,   133,   140,   140,   nil,   133,   133,   nil,
   nil,   nil,   nil,   140,   nil,   140,   140,   133,   nil,   nil,
   140,   140,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   140 ]

racc_action_pointer = [
     4,     2,   nil,   -25,   509,    17,     9,    -7,   -14,    11,
    -6,   522,    -6,   nil,   nil,   nil,   nil,    -4,     3,    -6,
     0,     3,     4,     8,   nil,   nil,   540,    27,    16,   -21,
   nil,    14,    45,    22,   nil,   nil,   nil,   nil,    31,    22,
   492,    74,    80,    88,    94,   102,   nil,   nil,   nil,   nil,
   nil,    23,    39,   nil,   nil,    51,   nil,    86,    30,   154,
   nil,   160,    80,   168,   553,   174,   182,   234,   240,   248,
   254,   262,   314,   nil,   nil,   320,   328,   334,   342,   394,
   400,   408,   nil,    86,   nil,   nil,   nil,   571,   414,   nil,
   nil,   nil,   nil,   nil,    85,   nil,    50,   nil,    92,    97,
   -28,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    75,    68,   422,
    58,   nil,    -2,   nil,   584,   nil,   474,   106,   nil,    88,
   -32,    86,   nil,   602,   480,   166,    94,    75,   nil,   nil,
   615,   101,   nil ]

racc_action_default = [
   -66,   -66,    -1,   -66,   -66,   -66,   -66,    -4,   -66,   -66,
   -66,   -19,   -66,   -22,   -23,   -24,   -25,   -66,   -66,   -66,
   -66,   -66,   -66,   -66,   -65,   143,   -66,   -66,   -66,   -13,
    -3,   -66,   -66,   -66,   -20,   -21,   -26,   -27,   -60,   -66,
   -35,   -66,   -66,   -66,   -66,   -66,   -59,   -61,   -62,   -63,
   -64,   -66,   -66,   -33,   -34,   -66,    -5,   -66,   -66,   -66,
   -15,   -66,   -66,   -66,   -66,   -66,   -66,   -66,   -66,   -66,
   -66,   -66,   -66,   -47,   -48,   -66,   -66,   -66,   -66,   -66,
   -66,   -66,   -36,   -66,   -46,   -49,   -51,   -66,   -66,    -2,
    -6,    -7,    -8,    -9,   -66,   -11,   -14,   -16,   -17,   -66,
   -66,   -38,   -39,   -40,   -41,   -42,   -43,   -44,   -45,   -50,
   -53,   -54,   -55,   -56,   -57,   -58,   -37,   -66,   -66,   -66,
   -66,   -18,   -52,   -28,   -66,   -30,   -66,   -66,   -12,   -66,
   -66,   -66,   -29,   -66,   -66,   -66,   -66,   -66,   -10,   -31,
   -66,   -66,   -32 ]

racc_goto_table = [
     9,    10,    12,    90,    28,    29,     6,    34,    10,    12,
   121,     1,     2,   nil,   nil,   nil,   nil,   nil,    52,    53,
   nil,   nil,    55,    10,    12,   nil,   nil,   nil,   nil,   nil,
    56,   nil,   nil,   nil,   121,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    95,    29,   nil,   nil,   nil,   nil,
   100,    10,    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   138,   nil,   117,    10,    12,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    39,    51,   nil,   nil,    54,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    60,   nil,    62,   128,    29,   nil,   nil,
   129,    10,    12,    82,    83,    84,    85,    86,   nil,   136,
    10,    12,   nil,   nil,   nil,   nil,   141,    10,    12,   nil,
   nil,    96,   nil,    97,   nil,    99,   nil,   101,   102,   103,
   104,   105,   106,   107,   108,   nil,   nil,   109,   110,   111,
   112,   113,   114,   115,   nil,   nil,   nil,   nil,   nil,   nil,
   118,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   127,   nil,   nil,   nil,   nil,   nil,   nil,   130,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   137 ]

racc_goto_check = [
     4,     9,    10,     7,     6,     9,     3,     4,     9,    10,
    11,     1,     2,   nil,   nil,   nil,   nil,   nil,     9,     9,
   nil,   nil,     4,     9,    10,   nil,   nil,   nil,   nil,   nil,
     3,   nil,   nil,   nil,    11,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     6,     9,   nil,   nil,   nil,   nil,
     4,     9,    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     7,   nil,     4,     9,    10,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     8,     8,   nil,   nil,     8,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     8,   nil,     8,     6,     9,   nil,   nil,
     4,     9,    10,     8,     8,     8,     8,     8,   nil,     4,
     9,    10,   nil,   nil,   nil,   nil,     4,     9,    10,   nil,
   nil,     8,   nil,     8,   nil,     8,   nil,     8,     8,     8,
     8,     8,     8,     8,     8,   nil,   nil,     8,     8,     8,
     8,     8,     8,     8,   nil,   nil,   nil,   nil,   nil,   nil,
     8,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     8,   nil,   nil,   nil,   nil,   nil,   nil,     8,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     8 ]

racc_goto_pointer = [
   nil,    11,    12,     3,    -4,   nil,    -4,   -54,    82,    -3,
    -2,   -88,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,    13,   nil,   nil,     7,   nil,   nil,   nil,    38,
    46,    32,    11,    14,    15,    16,    17,    18,    40 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 59, :_reduce_1,
  5, 60, :_reduce_2,
  3, 60, :_reduce_3,
  1, 61, :_reduce_4,
  3, 61, :_reduce_5,
  4, 63, :_reduce_6,
  1, 65, :_reduce_7,
  1, 65, :_reduce_8,
  1, 65, :_reduce_9,
  6, 65, :_reduce_10,
  3, 64, :_reduce_11,
  5, 64, :_reduce_12,
  1, 64, :_reduce_13,
  3, 64, :_reduce_14,
  3, 68, :_reduce_15,
  4, 68, :_reduce_16,
  3, 69, :_reduce_17,
  4, 69, :_reduce_18,
  1, 62, :_reduce_19,
  2, 62, :_reduce_20,
  2, 70, :_reduce_21,
  1, 70, :_reduce_22,
  1, 70, :_reduce_23,
  1, 70, :_reduce_24,
  1, 70, :_reduce_25,
  2, 70, :_reduce_26,
  2, 70, :_reduce_27,
  5, 71, :_reduce_28,
  7, 71, :_reduce_29,
  5, 72, :_reduce_30,
  9, 73, :_reduce_31,
  11, 73, :_reduce_32,
  2, 74, :_reduce_33,
  2, 75, :_reduce_34,
  1, 66, :_reduce_35,
  2, 66, :_reduce_36,
  3, 66, :_reduce_37,
  3, 66, :_reduce_38,
  3, 66, :_reduce_39,
  3, 66, :_reduce_40,
  3, 66, :_reduce_41,
  3, 66, :_reduce_42,
  3, 66, :_reduce_43,
  3, 66, :_reduce_44,
  3, 66, :_reduce_45,
  2, 66, :_reduce_46,
  2, 66, :_reduce_47,
  2, 66, :_reduce_48,
  2, 66, :_reduce_49,
  3, 66, :_reduce_50,
  2, 66, :_reduce_51,
  4, 66, :_reduce_52,
  3, 66, :_reduce_53,
  3, 66, :_reduce_54,
  3, 66, :_reduce_55,
  3, 66, :_reduce_56,
  3, 66, :_reduce_57,
  3, 66, :_reduce_58,
  1, 66, :_reduce_59,
  1, 76, :_reduce_60,
  1, 76, :_reduce_61,
  1, 76, :_reduce_62,
  1, 76, :_reduce_63,
  1, 76, :_reduce_64,
  1, 67, :_reduce_65 ]

racc_reduce_n = 66

racc_shift_n = 143

racc_token_table = {
  false => 0,
  :error => 1,
  "TkId" => 2,
  "TkNum" => 3,
  "TkCaracter" => 4,
  ParCierra => 5,
  ParAbre => 6,
  CorcheteAbre => 7,
  CorcheteCierre => 8,
  Concatenacion => 9,
  Shift => 10,
  SiguienteCar => 11,
  AnteriorCar => 12,
  ValorAscii => 13,
  Suma => 14,
  Resta => 15,
  Mult => 16,
  Div => 17,
  Mod => 18,
  :UMINUS => 19,
  Disyuncion => 20,
  Conjuncion => 21,
  Negacion => 22,
  Menor => 23,
  MenorIgual => 24,
  Mayor => 25,
  MayorIgual => 26,
  Igual => 27,
  Desigualdad => 28,
  With => 29,
  Begin => 30,
  End => 31,
  TkArray => 32,
  Var => 33,
  Of => 34,
  Int => 35,
  Bool => 36,
  Char => 37,
  If => 38,
  Otherwise => 39,
  While => 40,
  For => 41,
  From => 42,
  To => 43,
  Step => 44,
  Read => 45,
  Print => 46,
  Coma => 47,
  Punto => 48,
  PuntoYComa => 49,
  DosPuntos => 50,
  Hacer => 51,
  Asignacion => 52,
  True => 53,
  False => 54,
  TkId => 55,
  TkNum => 56,
  TkCaracter => 57 }

racc_nt_base = 58

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"TkId\"",
  "\"TkNum\"",
  "\"TkCaracter\"",
  "\")\"",
  "\"(\"",
  "\"[\"",
  "\"]\"",
  "\"::\"",
  "\"$\"",
  "\"++\"",
  "\"--\"",
  "\"#\"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "UMINUS",
  "\"\\\\/\"",
  "\"/\\\\\"",
  "\"not\"",
  "\"<\"",
  "\"<=\"",
  "\">\"",
  "\">=\"",
  "\"=\"",
  "\"/=\"",
  "\"with\"",
  "\"begin\"",
  "\"end\"",
  "\"array\"",
  "\"var\"",
  "\"of\"",
  "\"int\"",
  "\"bool\"",
  "\"char\"",
  "\"if\"",
  "\"otherwise\"",
  "\"while\"",
  "\"for\"",
  "\"from\"",
  "\"to\"",
  "\"step\"",
  "\"read\"",
  "\"print\"",
  "\",\"",
  "\".\"",
  "\";\"",
  "\":\"",
  "\"->\"",
  "\"<-\"",
  "\"true\"",
  "\"false\"",
  "\"tkid\"",
  "\"tknum\"",
  "\"tkcaracter\"",
  "$start",
  "S",
  "Bloque",
  "ListaDeclaraciones",
  "Instrucciones",
  "Declaracion",
  "ListaId",
  "Tipo",
  "Expresion",
  "Id",
  "Asignacion",
  "ListaCorchetes",
  "Instruccion",
  "Condicional",
  "IteracionInd",
  "IteracionDet",
  "Entrada",
  "Salida",
  "Literal" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'Parser.y', 91)
  def _reduce_1(val, _values, result)
    result = S.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 95)
  def _reduce_2(val, _values, result)
    result = Bloque.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 96)
  def _reduce_3(val, _values, result)
    result = Bloque.new(nil, val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 100)
  def _reduce_4(val, _values, result)
    result = DeclaracionesList.new(val[0], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 101)
  def _reduce_5(val, _values, result)
    result = DeclaracionesList.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 106)
  def _reduce_6(val, _values, result)
    result = Declaracion.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 110)
  def _reduce_7(val, _values, result)
    result = TipoInt.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 111)
  def _reduce_8(val, _values, result)
    result = TipoBool.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 112)
  def _reduce_9(val, _values, result)
    result = TipoChar.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 113)
  def _reduce_10(val, _values, result)
    result = TipoArray.new(val[2], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 117)
  def _reduce_11(val, _values, result)
    result = ListaIdentificadores.new(val[0], nil , val[2])  
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 118)
  def _reduce_12(val, _values, result)
    result = ListaIdentificadores.new(val[0], val[2], val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 119)
  def _reduce_13(val, _values, result)
    result = ListaIdentificadores.new(val[0], nil, nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 120)
  def _reduce_14(val, _values, result)
    result = ListaIdentificadores.new(val[0], val[2], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 124)
  def _reduce_15(val, _values, result)
    result = AsignacionA.new(val[0], val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 125)
  def _reduce_16(val, _values, result)
    result = AsignacionB.new(val[0], val[2], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 129)
  def _reduce_17(val, _values, result)
    result = Corchetes.new(val[1],nil  )
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 130)
  def _reduce_18(val, _values, result)
    result = Corchetes.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 135)
  def _reduce_19(val, _values, result)
    result = ListaIns.new(val[0], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 136)
  def _reduce_20(val, _values, result)
    result = ListaIns.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 140)
  def _reduce_21(val, _values, result)
    result = Instruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 141)
  def _reduce_22(val, _values, result)
    result = Instruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 142)
  def _reduce_23(val, _values, result)
    result = Instruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 143)
  def _reduce_24(val, _values, result)
    result = Instruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 144)
  def _reduce_25(val, _values, result)
    result = Instruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 145)
  def _reduce_26(val, _values, result)
    result = Instruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 146)
  def _reduce_27(val, _values, result)
    result = Instruccion.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 151)
  def _reduce_28(val, _values, result)
    result = Condicional.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 152)
  def _reduce_29(val, _values, result)
    result = CondicionalOth.new(val[1], val[3], val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 156)
  def _reduce_30(val, _values, result)
    result = IteracionInd.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 160)
  def _reduce_31(val, _values, result)
    result = IteracionDet.new(val[1], val[3], val[5], val[7], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 161)
  def _reduce_32(val, _values, result)
    result = IteracionDet.new(val[1], val[3], val[5], val[7], val[9])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 165)
  def _reduce_33(val, _values, result)
    result = Entrada.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 169)
  def _reduce_34(val, _values, result)
    result = Salida.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 174)
  def _reduce_35(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 175)
  def _reduce_36(val, _values, result)
    result = Negativo.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 176)
  def _reduce_37(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 177)
  def _reduce_38(val, _values, result)
    result = PuntoParser.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 178)
  def _reduce_39(val, _values, result)
    result = Sumar.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 179)
  def _reduce_40(val, _values, result)
    result = Restar.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 180)
  def _reduce_41(val, _values, result)
    result = Multiplicacion.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 181)
  def _reduce_42(val, _values, result)
    result = Division.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 182)
  def _reduce_43(val, _values, result)
    result = Modulo.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 183)
  def _reduce_44(val, _values, result)
    result = Or.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 184)
  def _reduce_45(val, _values, result)
    result = And.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 185)
  def _reduce_46(val, _values, result)
    result = Not.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 186)
  def _reduce_47(val, _values, result)
    result = CaracterSiguiente.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 187)
  def _reduce_48(val, _values, result)
    result = CaracterAnterior.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 188)
  def _reduce_49(val, _values, result)
    result = ValorAsciiParser.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 189)
  def _reduce_50(val, _values, result)
    result = Concatenar.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 190)
  def _reduce_51(val, _values, result)
    result = ShiftParser.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 191)
  def _reduce_52(val, _values, result)
    result = Indexacion.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 192)
  def _reduce_53(val, _values, result)
    result = MenorQue.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 193)
  def _reduce_54(val, _values, result)
    result = MenorIgualQue.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 194)
  def _reduce_55(val, _values, result)
    result = MayorQue.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 195)
  def _reduce_56(val, _values, result)
    result = MayorIgualQue.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 196)
  def _reduce_57(val, _values, result)
    result = Igualdad.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 197)
  def _reduce_58(val, _values, result)
    result = Desigual.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 198)
  def _reduce_59(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 202)
  def _reduce_60(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 203)
  def _reduce_61(val, _values, result)
    result = LitNum.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 204)
  def _reduce_62(val, _values, result)
    result = LitChar.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 205)
  def _reduce_63(val, _values, result)
    result = LitTrue.new("true")
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 206)
  def _reduce_64(val, _values, result)
    result = LitFalse.new("false")
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 210)
  def _reduce_65(val, _values, result)
    result = Identificador.new(val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
